<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    r_A=len(A)
    c_A=len(A[0])
    
    
    r_B=len(B)
    c_B=len(B[0])
    
    if c_A!=r_B:
        return 'Matrix Multiplication is not possible'
    
    Matrix=[]
    for row in range(r_A):
        row_mat=[]
        for col in range(c_B):
            summ=0
            for ind in range(r_B):
                summ+=A[row][ind]*B[ind][col]
                
            row_mat.append(summ)
        Matrix.append(row_mat)
        
    return Matrix
            
A=[[1,2],
   [3,4]]
B=[[1,2],
   [3,4]]    
matrix_mul(A, B)

[[7, 10], [15, 22]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [27]:

#https://stackoverflow.com/questions/57892112/select-a-number-randomly-with-probability-proportional-to-its-magnitude-from-the
from random import uniform
import random
import numpy as np
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    summ=sum(A)

    nor_A=[j/summ for j in A] 
        
    #cummulative sum:
    cum_A=[]
    c=0
    for c_val in nor_A:
        cum_A.append(c+c_val)
        c+=c_val
        
    #picking value:
    r=random.random()
    pick_vals=[]
    for k in range(len(cum_A)):
        if r<cum_A[k]:
            return A[k]


def sampling_based_on_magnitued(A):
    final=[]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        final.append(number)

    return final


In [28]:

rand_nums=sampling_based_on_magnitued(A)
print(rand_nums)
#print(np.unique(rand_nums,return_counts=True))

[100, 28, 13, 28, 13, 27, 79, 100, 79, 100, 79, 10, 79, 45, 45, 100, 45, 13, 45, 79, 27, 45, 100, 100, 100, 27, 45, 79, 100, 28, 27, 27, 79, 100, 79, 79, 27, 28, 100, 45, 45, 28, 79, 27, 100, 13, 45, 45, 27, 27, 100, 27, 27, 45, 79, 13, 79, 45, 100, 79, 79, 100, 100, 28, 45, 28, 45, 100, 5, 13, 100, 100, 27, 79, 100, 79, 28, 79, 100, 100, 100, 79, 100, 79, 28, 79, 79, 27, 28, 100, 5, 79, 45, 100, 100, 45, 79, 28, 79]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    res=[ i for i in String]
    
    for j in range(len(res)):
        if res[j].isdigit():
            res[j]='#'
        else:
            res[j]=''
            
    
    return(''.join(res)) # modified string which is after replacing the # with digits

In [ ]:

String=input('enter the string name:')
replace_digits(String)

enter the string name:#2a$#b%c%561# 


'####'

In [ ]:
String=input('enter the string name:')
replace_digits(String)

enter the string name:naveen


''

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [34]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    
    asc_list=sorted(list(zip(students,marks)) ,key=lambda z:z[1])
    
    # write code for computing top 5 students
    print('top 5 students:')
    for i,j in asc_list[::-1][:5]:
        print(i,':',j)
    
    # write code for computing  least 5 students
    print()
    least_5_students =asc_list[:5]
    print('least 5 students:')
    for i ,j in asc_list[:5]:
        print(i,j)
    
    # write code for computing  students between 25 and 75
    print()
    print('students between 25 and 75:')

    maxx = max(marks)
    minn = min(marks)
    diff = maxx - minn
    pre_25 = diff*0.25
    pre_75 = diff*0.75    

    for i ,j in asc_list:
        if pre_25<j<pre_75:
            print(i,j)
            

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

display_dash_board(students, marks)


top 5 students:
student8 : 98
student10 : 80
student2 : 78
student5 : 48
student7 : 47

least 5 students:
student3 12
student4 14
student9 35
student6 43
student1 45

students between 25 and 75:
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    
    close_points=[]
    for i,j in S:
        dis_num=i*P[0]+j*P[1]
        dis_dem=(math.sqrt(i**2+j**2)) * (math.sqrt(P[0]**2 +P[1]**2 ))
        cosine=math.acos(dis_num/dis_dem)
        close_points.append(cosine)
    all_points=dict(zip(S,close_points))
    sort=sorted(all_points.items(),key=lambda z:z[1])
    
    for keys,values in sort[:5]:
        print(keys)
        
        


S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S, P)
 #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,lines):
    # your code
    red_val=[]
    blu_val=[]
    
    for each_line in lines:
        listy=[float(i.strip()) for i in re.split('x|y',each_line)]
        eq=listy
        
        rd=[]
        bl=[]

        for i in range(len(listy)):
            
            
            r=(red[i][0]*eq[0]) + (red[i][1]*eq[1]) + (eq[2])
            b=(blue[i][0]*eq[0]) + (blue[i][1]*eq[1]) + (eq[2])
            rd.append(r)
            bl.append(b)
        red_val.append(rd)
        blu_val.append(bl)

    all_reds=[all(b>0 for b in a)for a in red_val]
    all_blus=[all(b<0 for b in a)for a in blu_val]
    
    for i in range(len(all_reds)):
        if (all_reds[i]==True and all_blus[i]==True):
            print('YES')
        else:
            print('NO')

    

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Line=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

i_am_the_one(Red,Blue,Line)

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure


def curve_smoothing(listty):
  store=0
  index=0
  last=0
  den=0


  listty=listty.split(',')
  for ind,i in enumerate(listty):
    
    if (i!="_") and (ind==0):
      store=int(i)

    elif  (i!="_") and (int(i)>0):

      for indd,j in enumerate(range(index,ind+1)):
          listty[j]=(store+last+int(i))/(ind+1-index)
          #print(last,int(i),ind+1-index,list1[j])

      index=ind
      last=int(listty[index])

    elif  (i=='_') and (ind==len(listty)-1):
      for k in range(index+1,len(listty)):
        if last==0:
          last=int(listty[0])
          listty[0]=(last)/(len(listty[index:]))

        listty[k]=(last)/(len(listty[index:]))

  final=[int(i) for i in listty]  
  return final




string=  "_,_,30,_,_,_,50,_,_"
s2="40,_,_,_,60"
s3="80,_,_,_,_"
s4="_,_,_,24"


print(curve_smoothing(string))

print(curve_smoothing(s2))
print(curve_smoothing(s3))
print(curve_smoothing(s4))

[10, 10, 12, 12, 12, 12, 12, 4, 4]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[6, 6, 6, 6]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    F=sorted(list(set([A[i][0] for i in range(len(A))])))
    S=sorted(list(set([A[i][1] for i in range(len(A))])))
    
    S_cnts=[0,0,0]
    for j in A:
        if j[1]=='S1':
            S_cnts[0]+=1
        if j[1]=='S2':
            S_cnts[1]+=1
        if j[1]=='S3':
            S_cnts[2]+=1
            
    #print(S_cnt)
    F_cnts=[]
    for i in F:
        F_ind=[0,0,0]
        for k in A:
            if k[0]==i and k[1]=='S1':
                F_ind[0]+=1
            elif k[0]==i and k[1]=='S2':
                F_ind[1]+=1
            elif k[0]==i and k[1]=='S3':
                F_ind[2]+=1
                
        F_cnts.append(F_ind)
    #print(F_cnt)
    
    for i in range(len(F)):
        print('P(F={0}|S=S1)={F1}/{S1}, P(F={0}|S=S2)={F2}/{S2}, P(F={0}|S=S3)={F3}/{S3}'.
              format(F[i],F1=F_cnts[i][0],S1=S_cnts[0],F2=F_cnts[i][1],S2=S_cnts[1],F3=F_cnts[i][2],S3=S_cnts[2]))
    
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S=S1)=1/4, P(F=F1|S=S2)=1/3, P(F=F1|S=S3)=0/3
P(F=F2|S=S1)=1/4, P(F=F2|S=S2)=1/3, P(F=F2|S=S3)=1/3
P(F=F3|S=S1)=0/4, P(F=F3|S=S2)=1/3, P(F=F3|S=S3)=1/3
P(F=F4|S=S1)=1/4, P(F=F4|S=S2)=0/3, P(F=F4|S=S3)=1/3
P(F=F5|S=S1)=1/4, P(F=F5|S=S2)=0/3, P(F=F5|S=S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    
    S1=S1.split()
    S2=S2.split()
    a=[]
    for i in S1:
        if i in S2:
            a.append(i)
    print(len(a))
    b=[]
    c=[]
    for i in range(len(S1)):
        if S1[i]!=S2[i]:
            b.append(S1[i])
            c.append(S2[i])
            
    print(b)
    print(c)
            


S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
string_features(S1, S2)


7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math
# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    total=0
    for i in range(len(A)):
        ind= ((A[i][0])*(math.log10(A[i][1]))) + ((1-A[i][0])*(math.log10(1-A[i][1])))
        total+=ind
    
    loss=-(total/8)
    
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

print(compute_log_loss(A))


0.42430993457031635
